### ISSUE TITLE
Please consider renaming the project to sddm-gentoo-black-theme

### ISSUE THREAD

**Issue by Polynomial-C** [lebarondemerde/sddm-gentoo-black-theme#2]
Right now it's not obvious from the project name that this is a theme for sddm login manager. A rename would improve this.
I plan to add this theme to Gentoo but I cannot give the package the current project's name as it is too generic.

**Comment by lebarondemerde** [comment]
Hi,

I do agree and renamed the project.

Thank you! 👍

**Comment by Polynomial-C** [comment]
And thank you for the rename.
